### ISSUE TITLE
Problem for test

### ISSUE THREAD

**Issue by ShijianXu** [eriklindernoren/PyTorch-YOLOv3#141]
First, thank you for providing this awesome PyTorch code. 
I run `python3 test.py` and get the following RuntimeError:

> Compute mAP...
Detecting objects:   0%|                                                                                                                                                             Traceback (most recent call last):
  File "test.py", line 69, in <module>
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/xsj/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 40 and 5 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307

I don't know what's the problem is. Can you help me?

**Comment by ShijianXu** [comment]
Hi, I think your new datasets.py has bugs.
I found that you change the code a few hours ago. I replace the new `dataset.py` with your old `dataset.py` (yes, I cloned your old version yesterday), and I can successfully run `test.py`.

**Comment by eriklindernoren** [comment]
Hi. This should be fixed with this commit 96ae969.
