### ISSUE TITLE
torch.Size() takes an iterable of 'int' (item 1 is 'numpy.int64')

### ISSUE THREAD

**Issue by noahcao** [eriklindernoren/PyTorch-YOLOv3#191]
I'm trying to do the most simple command :
`python detect --image_folder ./data/samples`

But the error rises: 
`Performing object detection:
Traceback (most recent call last):
  File "detect.py", line 71, in <module>
    for batch_i, (img_paths, input_imgs) in enumerate(dataloader):
  File "/home/caojinkun/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/caojinkun/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/caojinkun/git/PyTorch-YOLOv3/utils/datasets.py", line 49, in __getitem__
    img, _ = pad_to_square(img, 0)
  File "/home/caojinkun/git/PyTorch-YOLOv3/utils/datasets.py", line 23, in pad_to_square
    img = F.pad(img, pad, "constant", value=pad_value)
  File "/home/caojinkun/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/nn/functional.py", line 1929, in pad
    return ConstantPadNd.apply(input, pad, value)
  File "/home/caojinkun/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/nn/_functions/padding.py", line 27, in forward
    output = input.new(input.size()[:(ctx.l_diff)] + new_dim).fill_(ctx.value)
TypeError: torch.Size() takes an iterable of 'int' (item 1 is 'numpy.int64')
`

I'm running under Python 3.5 and Pytorch0.4.0. I fixed some f-string error in models.py and detect.py to replace f"xxx{yyy}"  by "xxx{}".format(yyy) to make code runnable under py3.5

**Comment by noahcao** [comment]
Besides, my libs are supported by anaconda instead of pip. whether this would cause some problems?

**Comment by Hugh0120** [comment]
same error here, have you fixed it?

**Comment by Hugh0120** [comment]
change the version of PyTorch solved this

**Comment by hahakid** [comment]
@Hugh0120 what's the suggest pytorch version?

**Comment by Hugh0120** [comment]
> @Hugh0120 what's the suggest pytorch version?
pytorch                   1.1.0                   py3.6_0    pytorch
torchvision               0.3.0             py36_cuNone_1    pytorch

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
