### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wudi00** [eriklindernoren/PyTorch-YOLOv3#204]
I made datasets according to the training on Custom Dataset tutorial. But something went wrong.`Traceback (most recent call last):
  File "train.py", line 100, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/disk/wudi/PyTorch-YOLOv3/utils/datasets.py", line 133, in __getitem__
    img, targets = horisontal_flip(img, targets)
  File "/media/disk/wudi/PyTorch-YOLOv3/utils/augmentations.py", line 8, in horisontal_flip
    targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable`
There is my dataset:
/custum/images/1.jpg ...
/custum/labels/train/1.txt ...
/custum/labels/val/2.txt ...
/custum/classes.name
/custum/train.txt
/custum/val.txt
Is there something wrong? Thanks.

**Comment by yyx1107** [comment]
I use voc dateset to run the train.py and have the same error. @eriklindernoren

**Comment by wudi00** [comment]
@eriklindernoren And such error`
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    loss, outputs = model(imgs, targets)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/media/disk/wudi/PyTorch-YOLOv3/utils/utils.py", line 306, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered`, Thanks.

**Comment by yyx1107** [comment]
> @eriklindernoren The problem above has been solve, but another error` Traceback (most recent call last): File "train.py", line 108, in <module> loss, outputs = model(imgs, targets) File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/media/disk/wudi/PyTorch-YOLOv3/models.py", line 259, in forward x, layer_loss = module[0](x, targets, img_dim) File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/media/disk/wudi/PyTorch-YOLOv3/models.py", line 188, in forward ignore_thres=self.ignore_thres, File "/media/disk/wudi/PyTorch-YOLOv3/utils/utils.py", line 306, in build_targets noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0 RuntimeError: CUDA error: device-side assert triggered`, Thanks.

How did you solve it? I met the same problem.Thanks

**Comment by feiyuhuahuo** [comment]
Check your images, some of the images may be broken, you can print the image path when come with this problem. Use  try..... except...... @yyx1107 @wudi00

**Comment by wudi00** [comment]
@feiyuhuahuo I have 76 categories, I made datasets according to the training on Custom Dataset tutorial. And are there any other changes in the file?

**Comment by wudi00** [comment]
@yyx1107 It's my file path problem, I modified the txt file location.

**Comment by belowthetree** [comment]
I found that if the image'names contains 'jpg', it will be replace in datasets.py by 'path.replace("images", "labels").replace(".png", ".txt").replace(".jpg", ".txt")' . And some inputs will be 'None'


我猜测应该是图片的名字里有jpg等字样，会在这句’path.replace("images", "labels").replace(".png", ".txt").replace(".jpg", ".txt")‘代码中被替换名字，就会输入空的图片

**Comment by AndrewJSong** [comment]
问题处在数据增强上。打印传进网络的图片，在开启augment和multiscale以后，label中的x+w会超出1。
你可以尝试把train.py中的augment和multiscale设定为True测试
后续再调整代码完善功能

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
