### ISSUE TITLE
Training with non-square images (device-side assert triggered)

### ISSUE THREAD

**Issue by glefundes** [eriklindernoren/PyTorch-YOLOv3#277]
Hey guys!
I'm trying to train a model using images with dimensions of 240x80. Each label consists of 7 bounding boxes of different classes such as:

> 10 0.41041666666666665 0.55625 0.0375 0.1375
28 0.44375 0.55625 0.0375 0.1375
23 0.475 0.5625 0.041666666666666664 0.125
3 0.5229166666666667 0.5625 0.0375 0.125
2 0.55625 0.5625 0.029166666666666667 0.15
9 0.5854166666666667 0.5625 0.029166666666666667 0.15
6 0.6166666666666667 0.55625 0.03333333333333333 0.1625

For some reason that I cannot figure out, after very few batches on the first epoch, I aways get some variation of the error:

> Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/gabriel/.conda/envs/alpr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/models.py", line 262, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/gabriel/.conda/envs/alpr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/models.py", line 191, in forward
    ignore_thres=self.ignore_thres,
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/utils/utils.py", line 337, in build_targets
    iou_scores[b, best_n, gj, gi] = bbox_iou(pred_boxes[b, best_n, gj, gi], target_boxes, x1y1x2y2=False)
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/utils/utils.py", line 223, in bbox_iou
    iou = inter_area / (b1_area + b2_area - inter_area + 1e-16)
RuntimeError: CUDA error: device-side assert triggered

Or :

> /opt/conda/conda-bld/pytorch_1556653145446/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1556653145446/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [50,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1556653145446/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/gabriel/.conda/envs/alpr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/models.py", line 262, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/gabriel/.conda/envs/alpr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gabriel/Documentos/PyTorch-YOLOv3/models.py", line 194, in forward
    loss_x = self.mse_loss(x[obj_mask], tx[obj_mask])
RuntimeError: copy_if failed to synchronize: device-side assert triggered

Can anyone help? I've already parsed my annotations for possible errors but I don't think there are any.

**Comment by UMJCS** [comment]
same error @eriklindernoren 
Did you solve it rn? I also want to train on non-square image @glefundes

**Comment by Youggie** [comment]
check your dataset,make sure that your label is start with 0

**Comment by dang-qi** [comment]
> same error @eriklindernoren
> Did you solve it rn? I also want to train on non-square image @glefundes

Min Jie? I think I know you in Korea. To train on non-square image, I think you need to change a some stuff in YOLOlayer and build_target to make it support non-square input.

**Comment by smolendawid** [comment]
@UMJCS did you solve it?
