### ISSUE TITLE
IndexError: index 30 is out of bounds for dimension 1 with size 15 [中文/英文]

### ISSUE THREAD

**Issue by HughCraft** [eriklindernoren/PyTorch-YOLOv3#281]
```
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\pytorch\yolov3\models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\pytorch\yolov3\models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "E:\pytorch\yolov3\utils\utils.py", line 306, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
IndexError: index 30 is out of bounds for dimension 1 with size 15
```
Help me

**Comment by Gavin666Github** [comment]
how did you solve it ?

**Comment by HughCraft** [comment]
@Gavin666Github i set the batch to 1, and print the path of the image which is processing. and then delete the image and the lable.

**Comment by HughCraft** [comment]
> how did you solve it ?



> how did you solve it ?

 i set the batch to 1, and print the path of the image which is processing. and then delete the image and the lable.
