### ISSUE TITLE
 not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by lihongwei521** [eriklindernoren/PyTorch-YOLOv3#303]
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    data_config = parse_data_config(opt.data_config)
  File "/home/ubuntu/myfile/project/Pytorch_YoloV3/PyTorch-YOLOv3/utils/parse_config.py", line 34, in parse_data_config
    key, value = line.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by ioneliabuzatu** [comment]
Check your config file. If you have lines commented with ; semicolon  just replaced them with #

**Comment by shashankvkt** [comment]
data_config should be coco.data and not yolov3-tiny.cfg
