### ISSUE TITLE
error when test 

### ISSUE THREAD

**Issue by johnlanbor** [eriklindernoren/PyTorch-YOLOv3#32]
Namespace(batch_size=1, class_path='data/coco.names', conf_thres=0.8, config_path='config/yolov3.cfg', image_folder='data/samples', img_size=416, n_cpu=8, nms_thres=0.4, weights_path='weights/yolov3.weights')
Traceback (most recent call last):
  File "detect.py", line 41, in <module>
    model.load_weights(opt.weights_path)
  File "/mnt/disk_4T_1/Project/Detection/PyTorch-YOLOv3/old_source_code/PyTorch-YOLOv3/models.py", line 250, in load_weights
    bn_layer.running_mean.data.copy_(bn_rm)
  File "/home/qian/anaconda3/envs/py35torch/lib/python3.5/site-packages/torch/tensor.py", line 407, in data
    raise RuntimeError('cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?')
RuntimeError: cannot call .data on a torch.Tensor: did you intend to use autograd.Variable?

**Comment by eriklindernoren** [comment]
I believe you need tog upgrade to PyTorch 0.4.0
