### ISSUE TITLE
doesn't know, how to fix this

### ISSUE THREAD

**Issue by chandraveshchaudhari** [eriklindernoren/PyTorch-YOLOv3#329]
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/content/PyTorch-YOLOv3/utils/utils.py", line 301, in build_targets
    obj_mask[b, best_n, gj, gi] = 1
IndexError: index 2266 is out of bounds for dimension 2 with size 10

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
