### ISSUE TITLE
RuntimeError: shape '[1, 3, 6, 10, 10]' is invalid for input of size 1500

### ISSUE THREAD

**Issue by zak834** [eriklindernoren/PyTorch-YOLOv3#333]
Traceback (most recent call last):                                                                             File "train.py", line 105, in                                                                          loss, outputs = model(imgs, targets)                                                                       File "D:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__                         result = self.forward(*input, **kwargs)                                                                    File "D:\Ŀ▒▒▒▒\PyTorch-YOLOv3\PyTorch-YOLOv3\models.py", line 263, in forward                                  x, layer_loss = module[0](x, targets, img_dim)                                                             File "D:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__                         result = self.forward(*input, **kwargs)                                                                    File "D:\Ŀ▒▒▒▒\PyTorch-YOLOv3\PyTorch-YOLOv3\models.py", line 151, in forward                                  x.view(num_samples, self.num_anchors, self.num_classes + 5, grid_size, grid_size)                        RuntimeError: shape '[1, 3, 6, 10, 10]' is invalid for input of size 1500
--

**Comment by gsx0015** [comment]
Are you using your own dataset?, if yes,you need  fix Number of classes

**Comment by 121786404** [comment]
应该要修改配置文件吧

**Comment by Tathagatd96** [comment]
I am getting a similar error.  I am dealing with 117 classes on my custom dataset. I have set filters to 366 = (117 + 5) * 3 and classes to 117. But, get the same error. All other issues suggest to do the steps above nothing else. If anyone has find a solution, kindly comment.

**Comment by Damon2019** [comment]
Hello, did you solve this problem？

**Comment by Damon2019** [comment]
@Tathagatd96 Hello, did you solve this problem？

**Comment by AadeIT** [comment]
Hello, did you solve this problem？

**Comment by xiaoyuzhu666** [comment]
Hello, did you solve this problem？

**Comment by ThanhPham1987** [comment]
me too the same issue

**Comment by morgankohler** [comment]
Yeah, there is no clear guide for changing the cfg except for the tiny

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
