### ISSUE TITLE
IndexError: index 3810 is out of bounds for dimension 2 with size 15

### ISSUE THREAD

**Issue by q1367880593** [eriklindernoren/PyTorch-YOLOv3#350]
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "PyTorch-YOLOv3/models.py", line 260, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "PyTorch-YOLOv3/utils/utils.py", line 301, in build_targets
    obj_mask[b, best_n, gj, gi] = 1
IndexError: index 3810 is out of bounds for dimension 2 with size 15

**Comment by bhanukaManesha** [comment]
Check whether your x and y coordinates are the **center of the target bounding box** and not the top left corner

**Comment by yshany** [comment]
I have the similar issue with 'IndexError: index X is out of bounds for dimension 2 with size X'

**Comment by q1367880593** [comment]
my label not normalization to 0,1
