### ISSUE TITLE
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

### ISSUE THREAD

**Issue by Note-Liu** [eriklindernoren/PyTorch-YOLOv3#360]
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

**Comment by Note-Liu** [comment]
This problem has been solved!

**Comment by Termi303** [comment]
How did you solve it? I'm facing the same issue at the moment when trying to train custom dataset.

- macOS 10.13.6
- python 3.7.5

Full trace:

`termi303$ python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    logger = Logger("logs")
  File "/Users/.../PyTorch-YOLOv3/utils/logger.py", line 7, in __init__
    self.writer = tf.summary.FileWriter(log_dir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'
`

**Comment by 030jmk** [comment]
for anyone else running into this issue, refer to #327 and https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/930c5872eea3d22233805f3f693dd5c9a9892707

**Comment by chouxianyu** [comment]
thanks!

**Comment by Borda** [comment]
there is a better way, drop TensorFlow dependency completely, see #412
