### ISSUE TITLE
Why Traceback like this when run train.py

### ISSUE THREAD

**Issue by xwf12345678** [eriklindernoren/PyTorch-YOLOv3#370]
Traceback (most recent call last):
  File "D:\新建文件夹\PyTorch-YOLOv3\train.py", line 42, in <module>
    logger = Logger("logs")
  File "D:\新建文件夹\PyTorch-YOLOv3\utils\logger.py", line 7, in __init__
    self.writer = tf.summary.FileWriter(logdir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'.

Why the error happens

**Comment by visionxy** [comment]
I replaced tensorflow 2.0.0 with 1.9.0 and solved the problem
