### ISSUE TITLE
RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630

### ISSUE THREAD

**Issue by AadeIT** [eriklindernoren/PyTorch-YOLOv3#378]
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    loss, outputs = model(imgs, targets)
  File "D:\Anaconda\Anaconda_3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\pytoch\PyTorch-YOLOv3-master (3)\PyTorch-YOLOv3-master\models.py", line 269, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "D:\Anaconda\Anaconda_3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\pytoch\PyTorch-YOLOv3-master (3)\PyTorch-YOLOv3-master\models.py", line 153, in forward
    x.view(num_samples, self.num_anchors, self.num_classes + 5, grid_size, grid_size)
RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630
------------------------------------------------------------------
this is my error
please,help me

**Comment by ischansgithub** [comment]
same

**Comment by AadeIT** [comment]
Change your configuration file，find yolov3，A total of three
******************************************
[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=15    #change this 
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
classes=1
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
********************************

**Comment by AadeIT** [comment]
Change your configuration file，find [yolo]，A total of three

Here's the part code
*****************************************

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=15&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #change this，A total of three，（5+your classes num *6
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326
classes=1
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

*******************





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ischansgithub"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 中午1:28
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630 (#378)




same

**Comment by ischansgithub** [comment]
> Change your configuration file，find [yolo]，A total of three Here's the part code ***************************************** [convolutional] batch_normalize=1 size=3 stride=1 pad=1 filters=256 activation=leaky [convolutional] size=1 stride=1 pad=1 filters=15&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #change this，A total of three，（5+your classes num *6 activation=linear [yolo] mask = 0,1,2 anchors = 10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326 classes=1 num=9 jitter=.3 ignore_thresh = .7 truth_thresh = 1 random=1 *******************
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ischansgithub"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月24日(星期二) 中午1:28 收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;; 抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630 (#378) same — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Your answer solved my problem. Thank you!!!!

**Comment by AadeIT** [comment]
you're welcome
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ischansgithub"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 中午1:56
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630 (#378)



 
Change your configuration file，find [yolo]，A total of three Here's the part code ***************************************** [convolutional] batch_normalize=1 size=3 stride=1 pad=1 filters=256 activation=leaky [convolutional] size=1 stride=1 pad=1 filters=15&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; #change this，A total of three，（5+your classes num *6 activation=linear [yolo] mask = 0,1,2 anchors = 10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326 classes=1 num=9 jitter=.3 ignore_thresh = .7 truth_thresh = 1 random=1 *******************
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ischansgithub"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月24日(星期二) 中午1:28 收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;; 抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: shape '[2, 3, 6, 11, 11]' is invalid for input of size 3630 (#378) same — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Your answer solved my problem. Thank you!!!!
