### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by CaptainEven** [eriklindernoren/PyTorch-YOLOv3#39]
[Epoch 0/30, Batch 0/14658] [Losses: x 0.155323, y 0.153960, w 1.839854, h 1.919111, conf 2.058636, cls 2.145512, total 8.272396, recall: 0.00000]
Traceback (most recent call last):
  File "/mnt/diskb/even/yolov3_pytorch/train.py", line 100, in <module>
    model.seen += imgs.size(0)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'seen'

**Comment by MrWhiteHomeman** [comment]
Hello，I have the same problem，too. Did you solved it?

**Comment by MrWhiteHomeman** [comment]
Hello，I have the same problem，too. Did you solved it?@CaptainEven
