### ISSUE TITLE
 cmap = plt.get_cmap("tab20b")

### ISSUE THREAD

**Issue by Note-Liu** [eriklindernoren/PyTorch-YOLOv3#396]
Traceback (most recent call last):
  File "detect.py", line 91, in <module>
    cmap = plt.get_cmap("tab20b")
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/matplotlib/cm.py", line 176, in get_cmap
    % (name, ', '.join(sorted(cmap_d.keys()))))
ValueError: Colormap tab20b is not recognized. Possible values are: Accent,

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
