### ISSUE TITLE
Error about custom data training

### ISSUE THREAD

**Issue by ansebby** [eriklindernoren/PyTorch-YOLOv3#402]
I met error as below when I try to train the custom data(512*512 jpg images).
What is the problem? Please review my error message.
-------------------------------------------------------------------------------------------
>python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data --img_size 64

Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=64, model_def='config
/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ansebby/PyTorch-YOLOv3/utils/datasets.py", line 130, in __getitem__
    img, targets = horisontal_flip(img, targets)
  File "/home/ansebby/PyTorch-YOLOv3/utils/augmentations.py", line 8, in horisontal_flip
    targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable

**Comment by jchhuang** [comment]
Have you solve this problem，I meet the same as you

**Comment by ansebby** [comment]
Not yet. How about you?

2020년 1월 24일 (금) 오전 12:04, jchhuang <notifications@github.com>님이 작성:

**Comment by jzr0065** [comment]
check the names of your images to see whether it end with '.jpg' or '.png', lowercase and uppercase make difference.

**Comment by guancheng817** [comment]
> check the names of your images to see whether it end with '.jpg' or '.png', lowercase and uppercase make difference.

my dataset ends with 'png' and still appear the error, how should I modify?Thanks

**Comment by tienthegainz** [comment]
Modify [this line](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/datasets.py#L65):
```
path.lower().replace("images", "labels").replace(
                ".png", ".txt").replace(".jpg", ".txt").replace(".jpeg", ".txt").replace(".jpeg", ".txt")
```

**Comment by summeryumyee** [comment]
mark

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
