### ISSUE TITLE
Varying the number of input channels

### ISSUE THREAD

**Issue by stadtgiraffe** [eriklindernoren/PyTorch-YOLOv3#414]
Thank you for the great work!
I got it working for my greyscale images since they are expanded to a three dimensional RGB image. But I wondered if its possible to simply change the code so the pipeline takes only one channel and computes faster (or even multiple channels > 3 for detection of 3D objects in series of concatenated Images). 
And if yes, where do I have to change the code? 

Thanks for the help!

**Comment by sub2sub2** [comment]
how to solve it?

**Comment by atinesh-s** [comment]
I am facing similar issue, do you guys found any work around.

**Comment by atinesh-s** [comment]
For processing single channel below changes should be done in the code

1. Change` channels=1` in `config/yolov3-custom.cfg`

2. Update `line 86` in `utils/datasets.py` with desired image conversion mode
```
img = transforms.ToTensor()(Image.open(img_path).convert('1'))
```
https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes

**Comment by dipam7** [comment]
This doesn't work for me. I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/Dipam.Vasani/Desktop/virtual_environments/yolo3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/Dipam.Vasani/Desktop/projects_files/vision/final_yolo/PyTorch-YOLOv3/utils/datasets.py", line 130, in __getitem__
    img, targets = horisontal_flip(img, targets)
  File "/Users/Dipam.Vasani/Desktop/projects_files/vision/final_yolo/PyTorch-YOLOv3/utils/augmentations.py", line 8, in horisontal_flip
    targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable
```

Seems like single channel is not supported by just changing a few things.

**Comment by dipam7** [comment]
For point 2, the following change worked for me

```
img = transforms.ToTensor()(Image.open(img_path)
```
