### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by aabcbcacb6** [eriklindernoren/PyTorch-YOLOv3#423]
Reloaded modules: models, utils, utils.parse_config, utils.utils, utils.logger, utils.datasets, utils.augmentations, test
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/coco.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='config/yolov3.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
Traceback (most recent call last):

  File "<ipython-input-23-aae86f1549ee>", line 1, in <module>
    runfile('C:/Users/user/PyTorch-YOLOv3/train.py', wdir='C:/Users/user/PyTorch-YOLOv3')

  File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/user/PyTorch-YOLOv3/train.py", line 74, in <module>
    collate_fn=dataset.collate_fn,

  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)

  File "D:\Anaconda\lib\site-packages\torch\utils\data\sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))

ValueError: num_samples should be a positive integer value, but got num_samples=0

runfile('C:/Users/user/PyTorch-YOLOv3/train.py', wdir='C:/Users/user/PyTorch-YOLOv3')
Reloaded modules: models, utils, utils.parse_config, utils.utils, utils.logger, utils.datasets, utils.augmentations, test
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/coco.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='config/yolov3.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
Traceback (most recent call last):

  File "<ipython-input-24-aae86f1549ee>", line 1, in <module>
    runfile('C:/Users/user/PyTorch-YOLOv3/train.py', wdir='C:/Users/user/PyTorch-YOLOv3')

  File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/user/PyTorch-YOLOv3/train.py", line 74, in <module>
    collate_fn=dataset.collate_fn,

  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)

  File "D:\Anaconda\lib\site-packages\torch\utils\data\sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))

ValueError: num_samples should be a positive integer value, but got num_samples=0

**When I run train.py, it always shows this error. I had tried to search the answer for this , but I still couldn't solve this problem...**

**Comment by rohitrawat13396** [comment]
Could you please tell, how did you resolve this?

**Comment by Zzheng-6** [comment]
How to solve this problem?

**Comment by Zzheng-6** [comment]
i have solved ,my error is that my train.txt is empty.
