### ISSUE TITLE
Empty target tensors for training images without any objects

### ISSUE THREAD

**Issue by AjeyPaiK** [eriklindernoren/PyTorch-YOLOv3#424]
Hey, I'm using your code to run a baseline for my custom data. In the data, some images do not have my objects of interest, so their corresponding text files are empty. When the targets are being loaded into the model along with images, those with empty target tensors throw this error:

Traceback (most recent call last):
  File "train.py", line 106, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/ajey/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ajey/Desktop/pytorch/PyTorch-YOLOv3-master/models.py", line 257, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/ajey/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ajey/Desktop/pytorch/PyTorch-YOLOv3-master/models.py", line 186, in forward
    ignore_thres=self.ignore_thres,
  File "/home/ajey/Desktop/pytorch/PyTorch-YOLOv3-master/utils/utils.py", line 294, in build_targets
    best_ious, best_n = ious.max(0)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

P.S. This is my target tensor that is empty: tensor([], size=(0, 6)) torch.Size([0, 6])

Please help!!

**Comment by RGring** [comment]
@AjeyPaiK Did you find a workaround?

**Comment by mama110** [comment]
Do you solve this problem?

**Comment by Khalifa1997** [comment]
Solved it yet?

**Comment by JessonKang** [comment]
I meet same problem. My solution is that be sure"train.txt" and "valid.txt" file only include those image path not have my objects of interest.  It can avoid emtpy targe file be loaded into the model.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.

**Comment by smkamrul-hasan** [comment]
Did you solve this problem?
