### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Laudarisd** [eriklindernoren/PyTorch-YOLOv3#429]
```
2020-03-02 15:11:38.179054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-02 15:11:38.179065: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-02 15:11:38.179217: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-02 15:11:38.203099: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2020-03-02 15:11:38.203398: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7d26880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-02 15:11:38.203411: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-02 15:11:38.277318: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-02 15:11:38.277682: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7dac610 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-02 15:11:38.277697: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-03-02 15:11:38.277779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-02 15:11:38.277785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    model = Darknet(opt.model_def).to(device)
  File "/home/sudip/torch/pytorch_yolo/models.py", line 240, in __init__
    self.hyperparams, self.module_list = create_modules(self.module_defs)
  File "/home/sudip/torch/pytorch_yolo/models.py", line 74, in create_modules
    num_classes = int(module_def["classes"])
ValueError: invalid literal for int() with base 10: ''

```
Why did I get this error? 

help me please. Totally stuck here

**Comment by Laudarisd** [comment]
Sorry, I did mistake while editing .cfg file.

**Comment by morgankohler** [comment]
What was the problem?

**Comment by Zzheng-6** [comment]
Can you tell me what caused this problem? How to solve?

**Comment by Laudarisd** [comment]
Hello @morgankohler , @Zzheng-6 sorry for late response.
In my case I did mistake while editing `.cfg` file.
I followed this and it solved my problem.
If yolov3.cfg
Line 3: set batch=24, this means we will be using 24 images for every training step
Line 4: set subdivisions=8, the batch will be divided by 8 to decrease GPU VRAM requirements.
Line 603: set filters=(classes + 5)*3
Line 610: set classes=15, the number of classes in our training
Line 689: set filters=(classes + 5)*3
Line 696: set classes=15, the number of classes in our training
Line 776: set filters=(classes + 5)*3
Line 783: set classes=15, the number of classes in our training

And make sure that you have your data in right path with right format.

**Comment by Zzheng-6** [comment]
Thank you for your answer, I also had an error in the .cfg file, which has now been resolved. But I got this error ：
UnboundLocalError: local variable'result' referenced before assignment,
do you know how to solve it?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 中午12:22
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] ValueError: invalid literal for int() with base 10: '' (#429)





 
Hello @morgankohler , @Zzheng-6 sorry for late response.
 In my case I did mistake while editing .cfg file.
 I followed this and it solved my problem.
 If yolov3.cfg
 Line 3: set batch=24, this means we will be using 24 images for every training step
 Line 4: set subdivisions=8, the batch will be divided by 8 to decrease GPU VRAM requirements.
 Line 603: set filters=(classes + 5)*3
 Line 610: set classes=15, the number of classes in our training
 Line 689: set filters=(classes + 5)*3
 Line 696: set classes=15, the number of classes in our training
 Line 776: set filters=(classes + 5)*3
 Line 783: set classes=15, the number of classes in our training
 
And make sure that you have your data in right path with right format.

**Comment by Laudarisd** [comment]
I am not familiar with this error. In my understanding your batch size is high. Did you try to reduce your batch size?

**Comment by Zzheng-6** [comment]
I only used five images as an attempt to train, so I set the batch to 5.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 下午4:16
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] ValueError: invalid literal for int() with base 10: '' (#429)





 
I am not familiar with this error. In my understanding your batch size is high. Did you try to reduce your batch size?

**Comment by Laudarisd** [comment]
you can increase your datasets and try one more time.  I found that less datasets might cause this problem.

**Comment by Zzheng-6** [comment]
This time I used 32 data sets and still failed...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 下午4:59
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] ValueError: invalid literal for int() with base 10: '' (#429)





 
you can increase your datasets and try one more time.  I found that less datasets might cause this problem.

**Comment by Laudarisd** [comment]
Sorry for late response.

Did you solve your problem? what is the error this time?
