### ISSUE TITLE
YOLO index out of bounds IndexError for custom dataset

### ISSUE THREAD

**Issue by spatiallysaying** [eriklindernoren/PyTorch-YOLOv3#452]
After the below step for my custom dataset,I am getting the errors. Appreciate any suggestions. 
**$ python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data**

```
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
WARNING:tensorflow:From /content/PyTorch-YOLOv3/utils/logger.py:7: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/content/PyTorch-YOLOv3/utils/utils.py", line 301, in build_targets
    obj_mask[b, best_n, gj, gi] = 1
IndexError: index 10 is out of bounds for dimension 3 with size 10
```

**Comment by recusant7** [comment]
I meet the similar problem.
`Traceback (most recent call last):
  File "train.py", line 131, in <module>
    loss, outputs = model(imgs, targets)
  File "/opt/anaconda3/envs/cv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/recusant/Desktop/PyTorch-YOLOv3_kiki-master/models.py", line 260, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/opt/anaconda3/envs/cv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/recusant/Desktop/PyTorch-YOLOv3_kiki-master/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/Users/recusant/Desktop/PyTorch-YOLOv3_kiki-master/utils/utils.py", line 316, in build_targets
    tcls[b, best_n, gj, gi, target_labels] = 1
IndexError: index 6 is out of bounds for dimension 4 with size 1`

**Comment by AntoineMath** [comment]
**Check your labels:** 
By using batch_size=1 and printing the path of the loaded image, I figure out that I had this issue for **some labels that had mistakes** : some of the coords were greater than 1 (meaning the box is outside the image)

**Comment by AntoineMath** [comment]
@spatiallysaying Did you figure out where the pb came from ?

**Comment by markgao-916** [comment]
参考检测层的255计算方式，与class number有关

**Comment by balintbujtor** [comment]
I am having the same problem, were you able to find a solution?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
