### ISSUE TITLE
AttributeError: 'Darknet' object has no attribute 'copy'

### ISSUE THREAD

**Issue by X-funbean** [eriklindernoren/PyTorch-YOLOv3#454]
Hi! 
I'm trying to continue training by loading a pretrained '.pth' weights file, but encounter this error:

```
Traceback (most recent call last):
  File "/root/xufangbin/YOLO_mask_detect/train.py", line 89, in <module>
    model.load_state_dict(torch.load(opt.pretrained_weights))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 803, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'copy'
```

Anyone knows why? For it seems work well for others.

**Comment by X-funbean** [comment]
I save the whole model by torch.save(model), so I directly load the whole model as well, using `model = torch.load('yolov3.pth')
