### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by SEASKY-Master** [eriklindernoren/PyTorch-YOLOv3#460]
Namespace(batch_size=8, class_path='data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Compute mAP...
Detecting objects:   0%|                                                                       | 0/625 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test.py", line 98, in <module>
    batch_size=8,
  File "test.py", line 36, in evaluate
    for batch_i, (_,imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\tqdm\std.py", line 1108, in __iter__
    for obj in iterable:
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\pytorch\PyTorch-YOLOv3-master\PyTorch-YOLOv3-master\utils\datasets.py", line 86, in __getitem__
    img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
  File "D:\Software_Tool\Anaconda3\envs\pytorch_gpu\lib\site-packages\PIL\Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/e/pytorch/PyTorch-YOLOv3-master/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

Detecting objects:   0%|

**Comment by Flova** [comment]
It seems like in image is missing in your dataset or the path is broken in another way. Could you please send more information?
