### ISSUE TITLE
detect.py 出现model报错

### ISSUE THREAD

**Issue by xiaomujiang** [eriklindernoren/PyTorch-YOLOv3#481]
我运行下面的代码出现了报错， 是需要 把 f"conv_{module_i}",该成  "conv_{module_i}",还是什么问题导致的？
(pytor) [zhangshilin@JHL-q PyTorch-YOLOv3]$ sudo python detect.py --image_folder data/samples/
Traceback (most recent call last):
  File "detect.py", line 3, in <module>
    from models import *
  File "/hadoop/disk02/zhangshilin/pytorch/eriklindernoren_yolov3/PyTorch-YOLOv3/models.py", line 32
    f"conv_{module_i}",
                     ^
SyntaxError: invalid syntax

**Comment by liunian199** [comment]
很多syntaxerror，从训练到测试，你是只有detect报错？

**Comment by liunian199** [comment]
python版本需要3.7,3.5会出现以上问题
