### ISSUE TITLE
Modify YOLOv3 backbone from DarkNet to AdderNet

### ISSUE THREAD

**Issue by promach** [eriklindernoren/PyTorch-YOLOv3#482]
How to correctly modify https://github.com/eriklindernoren/PyTorch-YOLOv3 to use https://github.com/huawei-noah/AdderNet ?

The following [colab ipynb notebook](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb) is what I have so far with the helps of others:

https://colab.research.google.com/drive/1VCafwykgNKAO6144LssBFFy0TmruDNSE#scrollTo=W3e-WcVxnKfs

How to solve the error on this [models.py](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-models-py-L321) file ?

![addernet_error](https://user-images.githubusercontent.com/3324659/79001970-12d2ef00-7b82-11ea-9e2f-8c0f98fd0852.png)

```
Namespace(batch_size=8, class_path='data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    model.load_darknet_weights(opt.weights_path)
  File "/content/PyTorch-YOLOv3/models.py", line 321, in load_darknet_weights
    num_w = conv_layer.weight.numel()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'adder2d' object has no attribute 'weight'
```

**Comment by promach** [comment]
I have solved the above compilation error. 

However, why training [train.py](https://gist.githubusercontent.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33/raw/452e9109cd671b0ae805b9527510b496a6c41b11/train.py) always [stop at epoch 0](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb) ?

![yolo_addernet_epoch_0](https://user-images.githubusercontent.com/3324659/79100323-d4634d00-7d98-11ea-8b1d-ac8c16e85d19.png)

**Comment by promach** [comment]
I have solved the epoch 0 issue by using the advice given at https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-612288299

See the [latest ipynb file](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb)

However, I am still stuck at how the image dataloader works.

Note : I have already ran [voc_label.py](https://github.com/pjreddie/darknet/blob/master/scripts/voc_label.py#L57-L58)

![yolov3_dataloader_error](https://user-images.githubusercontent.com/3324659/79121985-32a82400-7dc9-11ea-8739-1973aa95802a.png)

**Comment by dabblle** [comment]
batch_size=4???

**Comment by promach** [comment]
@dabblle See https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-613362421 in which I am trying to reduce the [GPU memory usage footprint](https://colab.research.google.com/drive/1VCafwykgNKAO6144LssBFFy0TmruDNSE).

**Comment by dabblle** [comment]
Check your  resources of cpu???

**Comment by promach** [comment]
@dabblle I am asking about reducing GPU memory usage, not CPU resource usage. Or did I miss anything ?

**Comment by summeryumyee** [comment]
Hello,Promach .This is problem 'adder2d' object has no attribute 'weight',I changed the class adder2d __init__ method and self.weight = torch.nn.Parameter(nn.init.normal_(torch.randn(output_channel,input_channel,kernel_size,kernel_size)))But it reported an error "bool' object has no attribute 'numel"

**Comment by promach** [comment]
Using [yolov3-tiny.cfg](https://github.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg) also does not help in solving GPU out-of-memory issue.

Any advices ?

**Comment by promach** [comment]
@dabblle See https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/58#issuecomment-616986029

**Comment by dabblle** [comment]
sorry，i don't  know

**Comment by promach** [comment]
It seems like `_temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)` in [back-propagation equation of AdderNet](https://github.com/promach/PyTorch-YOLOv3/blob/addernet/adder.py#L29) had caused the surge in GPU memory usage.

I was told to either

1. decrease the tensors dimension, then increase the tensors dimension again or
2. increase the tensors dimensions and then use depth-wise convolution or
3. use mixed-precision training

I know I can use https://github.com/NVIDIA/apex for the mixed precision training.
However, I am not sure how to modify the code for suggestions 1 and 2 above.

**Comment by dabblle** [comment]
Sorry, I don't have any good advice for you。
maybe，you can try half-precision。
good luck！！

**Comment by Meriem-Bouagila** [comment]
@promach 
how did you solve the first issue?

**Comment by promach** [comment]
@Meriem-Bouagila See https://github.com/promach/PyTorch-YOLOv3/blob/addernet/adder.py

**Comment by Meriem-Bouagila** [comment]
@promach with any version of Python did you work please?

**Comment by promach** [comment]
@Meriem-Bouagila See https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-623064131

**Comment by promach** [comment]
VOC2007 is not the default dataset for YOLOv3, do I need to [re-create new anchors](https://github.com/pjreddie/darknet/issues/911) ?
