### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by lucheng07082221** [eriklindernoren/PyTorch-YOLOv3#5]
when I run train.py I got a error:
Traceback (most recent call last):
  File "/home/lc/Downloads/PyTorch-YOLOv3/train.py", line 88, in <module>
    loss += model(sub_imgs, sub_targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc/Downloads/PyTorch-YOLOv3/models.py", line 214, in forward
    x = module[0](x, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc/Downloads/PyTorch-YOLOv3/models.py", line 175, in forward
    loss_cls = self.class_scale * self.ce_loss(pred_cls, tcls)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/loss.py", line 759, in forward
    self.ignore_index, self.reduce)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1442, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 944, in log_softmax
    return torch._C._nn.log_softmax(input, dim)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
this error place is in :           
       def forward(self, x, targets=None):  
            elif module_def['type'] == 'yolo':
                x = module[0](x, targets)
                # If predictions: concatenate / if loss: add to total loss
                output = output + [x] if targets is None else output + x

**Comment by eriklindernoren** [comment]
Hi. I've made some changes to the training procedure and this should be fixed now. Can you try and run it again?

**Comment by pengzhiwang** [comment]
I have run your program. However, when i run "train", algorithm cannot converge. How to solve？
