### ISSUE TITLE
EOFError maybe caused by new version python3.8

### ISSUE THREAD

**Issue by yosunpeng** [eriklindernoren/PyTorch-YOLOv3#503]
# EOFError maybe caused by new version python3.8
Stopped at epoch 14. Have tried twice, not an occasional collapse.
ArchLinux, python3.8.1, torch 1.3.1, tensorflow 2.1.0
`
---- ETA 0:08:52.591164Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
with self._listener.accept() as conn:
File "/usr/lib/python3.8/multiprocessing/connection.py", line 465, in accept
deliver_challenge(c, self._authkey)
File "/usr/lib/python3.8/multiprocessing/connection.py", line 739, in deliver_challenge
response = connection.recv_bytes(256)        # reject large message
File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
buf = self._recv_bytes(maxlength)
File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
raise EOFError
EOFError
`             
Please help, thanks in advance!

**Comment by meifish** [comment]
I bump into the same error, and it's Python 3.8 as well.

**Comment by Flova** [comment]
This is weird. Did you update all dependencies? Is python3.9 an option?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
