### ISSUE TITLE
AttributeError: 'numpy.int32' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by SurPer-Y** [eriklindernoren/PyTorch-YOLOv3#515]
I get this error when I run the train.py, and I couldn't figure it out.
```
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    print(AsciiTable(ap_table).table)
  File "/home/wangliyue/.conda/envs/wangliyue/lib/python3.7/site-packages/terminaltables.py", line 223, in table
    padded_table_data = self.padded_table_data
  File "/home/wangliyue/.conda/envs/wangliyue/lib/python3.7/site-packages/terminaltables.py", line 210, in padded_table_data
    column_widths = self.column_widths
  File "/home/wangliyue/.conda/envs/wangliyue/lib/python3.7/site-packages/terminaltables.py", line 187, in column_widths
    widths[i] = max(widths[i], len(max(row[i].splitlines(), key=len)))
AttributeError: 'numpy.int32' object has no attribute 'splitlines'
```
maybe some package was not appropriate, but im not sure. T _ T...

**Comment by Flova** [comment]
Could you try to update all deps to the newest version?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
