### ISSUE TITLE
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat1' in call to _th_addmm_

### ISSUE THREAD

**Issue by BrunoSader** [eriklindernoren/PyTorch-YOLOv3#523]
Hey i'm having a little issue with the model.
I'm trying to train the model on my own dataset (my images and labels are in a hdf5 file).
I load them into a torch Dataset and then into a Dataloader and everything seems to be working fine.
But as soon as I start the training i'm greeted with an error that I dont understand. I checked the type of every tensor and they all seem to be DoubleTensor and float64 (my understanding is that its the same as double).

Here is the Traceback :
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/bsader/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/bsader/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/bsader/yemen-bombings-tracking/Detection/train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bsader/yemen-bombings-tracking/Detection/model.py", line 256, in forward
    x = module(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat1' in call to _th_addmm_
```

My error seems to be once I call forward on a Conv2d layer ?

imgs and targets are both DoubleTensor
```py         
imgs = Variable(imgs.to(device))
targets = Variable(targets.to(device), requires_grad=False).double()
loss, outputs = model(imgs, targets) #line where error occurs
```

```py
class DetectDataset(Dataset):
    def __init__(self, h5_file, img_size=416, augment=True, multiscale=True, normalized_labels=True):
        super(DetectDataset, self).__init__()
        self.h5_file = h5_file
        self.img_size = img_size
        self.max_objects = 100
        self.augment = augment
        self.multiscale = multiscale
        self.normalized_labels = normalized_labels
        self.min_size = self.img_size - 3 * 32
        self.max_size = self.img_size + 3 * 32
        self.batch_count = 0

    def __getitem__(self, idx):
        #---------
        #  Image
        #---------
        with h5py.File(self.h5_file, 'r') as f:
            gt = np.expand_dims(f['gt'][str(idx)][:, :] / 255., 0)
            labels = np.expand_dims(f['label'][str(idx)][:, :] / 255., 0)

            img = transforms.ToTensor()(gt[0])

            # print(idx)
            # print(img.dim())
            # print("---")

            # Handle images with less than three channels
            if len(img.shape) != 3:
                img = img.unsqueeze(0)
                img = img.expand((3, img.shape[1:]))

            _, h, w = img.shape
            h_factor, w_factor = (h, w) if self.normalized_labels else (1, 1)
            # Pad to square resolution
            img, pad = pad_to_square(img, 0)
            _, padded_h, padded_w = img.shape

            # ---------
            #  Label
            # ---------

            boxes = torch.from_numpy(labels[0]).double()
            # print(boxes.dim())
            # print("---")

            # Extract coordinates for unpadded + unscaled image
            x1 = w_factor * (boxes[:, 1] - boxes[:, 3] / 2)
            y1 = h_factor * (boxes[:, 2] - boxes[:, 4] / 2)
            x2 = w_factor * (boxes[:, 1] + boxes[:, 3] / 2)
            y2 = h_factor * (boxes[:, 2] + boxes[:, 4] / 2)
            # Adjust for added padding
            x1 += pad[0]
            y1 += pad[2]
            x2 += pad[1]
            y2 += pad[3]
            # Returns (x, y, w, h)
            boxes[:, 1] = ((x1 + x2) / 2) / padded_w
            boxes[:, 2] = ((y1 + y2) / 2) / padded_h
            boxes[:, 3] *= w_factor / padded_w
            boxes[:, 4] *= h_factor / padded_h

            targets = torch.zeros((len(boxes), 6))
            targets[:, 1:] = boxes

            return img, targets

    def __len__(self):
        with h5py.File(self.h5_file, 'r') as f:
            return len(f['label'])
```

I kept the collate_fn and the rest of the class is the same.

**Comment by BrunoSader** [comment]
```py
class DetectDataset(Dataset):
    def __init__(self, h5_file, img_size=416, augment=True, multiscale=True, normalized_labels=True):
        super(DetectDataset, self).__init__()
        self.h5_file = h5_file
        self.img_size = img_size
        self.max_objects = 100
        self.augment = augment
        self.multiscale = multiscale
        self.normalized_labels = normalized_labels
        self.min_size = self.img_size - 3 * 32
        self.max_size = self.img_size + 3 * 32
        self.batch_count = 0

    def __getitem__(self, idx):
        #---------
        #  Image
        #---------
        with h5py.File(self.h5_file, 'r') as f:
            gt = np.expand_dims(f['gt'][str(idx)][:, :] / 255., 0)
            labels = np.expand_dims(f['label'][str(idx)][:, :] / 255., 0)

            img = transforms.ToTensor()(gt[0])

            # print(idx)
            # print(img.dim())
            # print("---")

            # Handle images with less than three channels
            if len(img.shape) != 3:
                img = img.unsqueeze(0)
                img = img.expand((3, img.shape[1:]))

            _, h, w = img.shape
            h_factor, w_factor = (h, w) if self.normalized_labels else (1, 1)
            # Pad to square resolution
            img, pad = pad_to_square(img, 0)
            _, padded_h, padded_w = img.shape

            # ---------
            #  Label
            # ---------

            boxes = torch.from_numpy(labels[0]).double()
            # print(boxes.dim())
            # print("---")

            # Extract coordinates for unpadded + unscaled image
            x1 = w_factor * (boxes[:, 1] - boxes[:, 3] / 2)
            y1 = h_factor * (boxes[:, 2] - boxes[:, 4] / 2)
            x2 = w_factor * (boxes[:, 1] + boxes[:, 3] / 2)
            y2 = h_factor * (boxes[:, 2] + boxes[:, 4] / 2)
            # Adjust for added padding
            x1 += pad[0]
            y1 += pad[2]
            x2 += pad[1]
            y2 += pad[3]
            # Returns (x, y, w, h)
            boxes[:, 1] = ((x1 + x2) / 2) / padded_w
            boxes[:, 2] = ((y1 + y2) / 2) / padded_h
            boxes[:, 3] *= w_factor / padded_w
            boxes[:, 4] *= h_factor / padded_h

            targets = torch.zeros((len(boxes), 6))
            targets[:, 1:] = boxes

            return img, targets

    def __len__(self):
        with h5py.File(self.h5_file, 'r') as f:
            return len(f['label'])
```
I kept the collate_fn and the rest of the class is the same.

**Comment by voodoopotato** [comment]
basically your tensor is in float64 which is double. to fix this issue, call .float() in your collate_fn on both img and targets. I hope that will help

**Comment by BrunoSader** [comment]
Thanks that helped!
