### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by ThanhPham1987** [eriklindernoren/PyTorch-YOLOv3#543]
Hi all,
When i run train.py on custom data. I have issue:
---- Evaluating Model ----
Detecting objects:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 665/696 [04:12<00:11,  2.64it/s]
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    batch_size=8,
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/PyTorch-YOLOv3/test.py", line 36, in evaluate
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/venv/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/venv/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

What should i do?
Please help me 
Bets regards,
PeterPham

**Comment by Flova** [comment]
Seems like a path in your validation dataset is broken. 
These types of issures should be fixed with #600

**Comment by Flova** [comment]
Should be fixed in #600
