### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/coco/images/val2014/COCO_val2014_000000135057.jpg'

### ISSUE THREAD

**Issue by liupenglei** [eriklindernoren/PyTorch-YOLOv3#545]
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/home/liupenglei/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/liupenglei/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/liupenglei/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/liupenglei/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/liupenglei/test/erikinder-pytorch-yolov3/erikinder-PyTorch-YOLOv3/utils/datasets.py", line 88, in __getitem__
    img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
  File "/home/liupenglei/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")

FileNotFoundError: [Errno 2] No such file or directory: '/home/data/coco/images/val2014/COCO_val2014_000000135057.jpg'

**Comment by liupenglei** [comment]
Why?之前跑代码的时候没有出现这个问题，过了几天跑代码出现这个问题了，是什么原因呢

**Comment by ethan4335** [comment]
我遇到同样问题，你解决了吗

**Comment by Royee-Lyu** [comment]
Do you solve this problem? I met the same question

**Comment by ethan4335** [comment]
> Do you solve this problem? I met the same question

I have fixed all the problems and have trained on my one dataset. can u tell me how u process your dataset?

**Comment by ethan4335** [comment]
> Do you solve this problem? I met the same question

you may need to check the code:  "img_path = os.path.join(self.cfg.dataset_dir, img_path)" in dataset.py, which is not suitable for me and I have commented it, because I organize my dataset in this form: "(absolute path) (annotation)".

you can debug the dataset.py at this line and check the data path. this may work.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
