### ISSUE TITLE
IndexError: index 12 is out of bounds for dimension 3 with size 12

### ISSUE THREAD

**Issue by KennedyS1** [eriklindernoren/PyTorch-YOLOv3#563]
Hi,
I'm trying to train on a custom dataset with the following command (I already imported the dataset as explained on the README page) : `python3 -W ignore train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data --pretrained_weights weights/darknet53.conv.74 `

I then get the following output:
```
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights='weights/darknet53.conv.74')

---- [Epoch 0/100, Batch 0/8733] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 15           | 30           | 60           |
| loss       | 73.403946    | 78.282753    | 80.335953    |
| x          | 0.088992     | 0.101948     | 0.084489     |
| y          | 0.095129     | 0.077184     | 0.081166     |
| w          | 0.803945     | 2.697430     | 4.463502     |
| h          | 0.409478     | 0.266827     | 3.191754     |
| conf       | 71.233047    | 74.406235    | 71.822243    |
| cls        | 0.773355     | 0.733130     | 0.692793     |
| cls_acc    | 3.64%        | 6.58%        | 20.43%       |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.494283     | 0.534763     | 0.486230     |
| conf_noobj | 0.495459     | 0.515249     | 0.506433     |
+------------+--------------+--------------+--------------+
Total loss 232.0226593017578
---- ETA 1 day, 10:47:44.710238

---- [Epoch 0/100, Batch 1/8733] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 10           | 20           | 40           |
| loss       | 74.001816    | 76.860405    | 77.392807    |
| x          | 0.108189     | 0.094425     | 0.073333     |
| y          | 0.087850     | 0.090576     | 0.100583     |
| w          | 0.515292     | 1.338280     | 2.862950     |
| h          | 0.602044     | 0.298030     | 1.843629     |
| conf       | 71.897469    | 74.322563    | 71.816620    |
| cls        | 0.790970     | 0.716531     | 0.695697     |
| cls_acc    | 3.17%        | 10.99%       | 18.18%       |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.402904     | 0.539650     | 0.483922     |
| conf_noobj | 0.497968     | 0.515191     | 0.506361     |
+------------+--------------+--------------+--------------+
Total loss 228.25502014160156
---- ETA 23:19:50.734797
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/homes/doua/rhabsieger/miniconda3/envs/pytorchgpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/homes/doua/rhabsieger/data/scripts/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/homes/doua/rhabsieger/miniconda3/envs/pytorchgpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/homes/doua/rhabsieger/data/scripts/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/homes/doua/rhabsieger/data/scripts/PyTorch-YOLOv3/utils/utils.py", line 301, in build_targets
    obj_mask[b, best_n, gj, gi] = 1
IndexError: index 12 is out of bounds for dimension 3 with size 12
```

I tried to re-run the command and the number of batch I'm able to compute vary from time to time as well as the error message (sometime, I get the same error except for the last line where I get `IndexError: index 10 is out of bounds for dimension 3 with size 10`)

**Comment by balintbujtor** [comment]
Hi! I am having the same issue. Were you able to find a solution for this problem?

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
