### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 3 (while checking arguments for cudnn_convolution)

### ISSUE THREAD

**Issue by hank08tw** [eriklindernoren/PyTorch-YOLOv3#568]
Total loss 220.54208374023438
---- ETA 0:41:00.091045
Traceback (most recent call last):
  File "/home/zhanshihan/miniconda3/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/zhanshihan/miniconda3/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/zhanshihan/miniconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/zhanshihan/miniconda3/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanshihan/PyTorch-YOLOv3/models.py", line 252, in forward
    x = module(x)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/zhanshihan/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 3 (while checking arguments for cudnn_convolution)

Is there an easy way to get rid of this issue? I use customized pascal voc dataset but I keep getting this error when I finish training on the first iteration.
When I changed device = torch.device("cuda" if torch.cuda.is_available() else "cpu") to device=torch.device(0), there is still some error.

**Comment by rosagradilla19** [comment]
I have the same issue!

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
