### ISSUE TITLE
ValueError: Image size of 232524x82088 pixels is too large

### ISSUE THREAD

**Issue by czHappy** [eriklindernoren/PyTorch-YOLOv3#589]
When I run detect.py, the ValueError occurs:
Saving images:
(0) Image: 'data/samples/dog.jpg'
	+ Label: dog, Conf: 0.99335
	+ Label: bicycle, Conf: 0.99981
	+ Label: truck, Conf: 0.94229
Traceback (most recent call last):
  File "detect.py", line 141, in <module>
    plt.savefig(f"output/{filename}.png", bbox_inches="tight", pad_inches=0.0)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 723, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2105, in print_figure
    **kwargs)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 514, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 404, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/home/sk49/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 92, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 232524x82088 pixels is too large. It must be less than 2^16 in each direction.

To run the script in CentOS, I modify the detect.py as follows:

import matplotlib  
matplotlib.use('Agg')

#ax.imshow(img)

So could you tell me how to fix it?

**Comment by czHappy** [comment]
I have uncommented this line #ax.imshow(img)， it works.
