### ISSUE TITLE
TypeError: function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by jameshsu007** [eriklindernoren/PyTorch-YOLOv3#595]
I train on my custom datasets and got the following error info, any friend can help me? thks.
---- [Epoch 0/100, Batch 0/679] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 13           | 26           | 52           |
| loss       | 88.839783    | 69.247116    | 67.691887    |
| x          | 0.044801     | 0.061944     | 0.099748     |
| y          | 0.082612     | 0.095327     | 0.083998     |
| w          | 1.012468     | 1.041615     | 2.178569     |
| h          | 9.440170     | 3.921851     | 2.365185     |
| conf       | 77.568748    | 63.440166    | 62.246513    |
| cls        | 0.690989     | 0.686213     | 0.717876     |
| cls_acc    | 0.00%        | 25.00%       | 0.00%        |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.503630     | 0.443750     | 0.474314     |
| conf_noobj | 0.524622     | 0.461351     | 0.456555     |
+------------+--------------+--------------+--------------+
Total loss 225.77877807617188
---- ETA 0:13:03.743846
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/home/lianwei/anaconda3/envs/ai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/lianwei/anaconda3/envs/ai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/lianwei/anaconda3/envs/ai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/lianwei/anaconda3/envs/ai/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by Flova** [comment]
Maybe an image path is corrupted or the image could not be read using PIL.

Related issue: https://github.com/facebookresearch/maskrcnn-benchmark/issues/1025

**Comment by Flova** [comment]
The dataloader has been reworked. Could you try to reproduce this issue?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.

**Comment by alexcp99** [comment]
hi

When I executed the last command python train.py.... appear this error:

  File "train.py", line 99, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/home/acebolla/anaconda3/envs/yolotrain/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/acebolla/anaconda3/envs/yolotrain/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/acebolla/anaconda3/envs/yolotrain/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/acebolla/anaconda3/envs/yolotrain/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by jaagut** [comment]
Hi @alexcp99,
it seems like either you are using an old version of this PyTorch-YOLO implementation or a completely different implementation from another source code repository.

> File "train.py", line 99, in
for batch_i, (_, imgs, targets) in enumerate(dataloader):

This line looks like this: https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/ae6800d0170e64544aa5dcfbbf85df4ad3606fd0/pytorchyolo/train.py#L99

Besides, we stopped supporting Python 3.6 and now require at least Python 3.8, and we never recommended using anaconda.

Please double-check, if this is the correct repository.
If so, please FIRST update our repository (see Readme.md for this) and open a new Issue regarding your problem.

Thank you
