### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by Mffff666** [eriklindernoren/PyTorch-YOLOv3#621]
When I run python3 detect.py --image_folder data/samples/，I get the following warning:
Performing object detection:
Traceback (most recent call last):
  File "detect.py", line 75, in <module>
    for batch_i, (img_paths, input_imgs) in enumerate(dataloader):
  File "/home/maff/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/maff/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/maff/PyTorch-YOLOv3/utils/datasets.py", line 58, in __getitem__
    img, _ = self.transform((img, boxes))
  File "/home/maff/venv/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/maff/venv/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/maff/PyTorch-YOLOv3/utils/transforms.py", line 100, in __call__
    bb_targets[:, 1:] = transforms.ToTensor()(boxes)
  File "/home/maff/venv/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 76, in __call__
    return F.to_tensor(pic)
  File "/home/maff/venv/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 48, in to_tensor
    img = torch.from_numpy(pic.transpose((2, 0, 1)))
ValueError: axes don't match array
does anybody know how to solve it please?

**Comment by Flova** [comment]
Do you use grayscale images and does this also occur when you are using the images and the model delivered on the master?

**Comment by Mffff666** [comment]
Thank you to reply, sir.
I just try to run the inference and don't change the images in the sample folder.
I suspect that if it has something with the version of torch?





---Original---

**Comment by Flova** [comment]
I guess. You are on commit `c987f2f` right? 
I use Python 3.9 and my package versions are 
```
absl-py                0.11.0    Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
cachetools             3.1.1     Extensible memoizing collections and decorators
certifi                2020.12.5 Python package for providing Mozilla's CA Bundle.
chardet                4.0.0     Universal encoding detector for Python 2 and 3
cycler                 0.10.0    Composable style cycles
decorator              4.4.2     Decorators for Humans
future                 0.18.2    Clean single-source support for Python 3 and 2
google-auth            1.24.0    Google Authentication Library
google-auth-oauthlib   0.4.2     Google Authentication Library
grpcio                 1.34.0    HTTP/2-based RPC framework
idna                   2.10      Internationalized Domain Names in Applications (IDNA)
imageio                2.9.0     Library for reading and writing a wide range of image, video, scientific, and volumetric data formats.
imgaug                 0.4.0     Image augmentation library for deep neural networks
kiwisolver             1.3.1     A fast implementation of the Cassowary constraint solver
markdown               3.3.3     Python implementation of Markdown.
matplotlib             3.3.3     Python plotting package
networkx               2.5       Python package for creating and manipulating graphs and networks
nonechucks             0.4.0     nonechucks is a library that provides wrappers for PyTorch's datasets, samplers, and transforms to allow for dropping unwanted or invalid samples dynamically.
numpy                  1.19.5    NumPy is the fundamental package for array computing with Python.
oauthlib               3.1.0     A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
opencv-python          4.5.1.48  Wrapper package for OpenCV python bindings.
pillow                 8.1.0     Python Imaging Library (Fork)
profilehooks           1.12.0    Decorators for profiling/timing/tracing individual functions
protobuf               3.14.0    Protocol Buffers
pyasn1                 0.4.8     ASN.1 types and codecs
pyasn1-modules         0.2.8     A collection of ASN.1-based protocols modules.
pyparsing              2.4.7     Python parsing module
python-dateutil        2.8.1     Extensions to the standard Python datetime module
pywavelets             1.1.1     PyWavelets, wavelet transform module
requests               2.25.1    Python HTTP for Humans.
requests-oauthlib      1.3.0     OAuthlib authentication support for Requests.
rope                   0.18.0    a python refactoring library...
rsa                    4.4       Pure-Python RSA implementation
scikit-image           0.18.1    Image processing in Python
scipy                  1.6.0     SciPy: Scientific Library for Python
shapely                1.7.1     Geometric objects, predicates, and operations
six                    1.15.0    Python 2 and 3 compatibility utilities
tensorboard            2.4.0     TensorBoard lets you watch Tensors Flow
tensorboard-plugin-wit 1.7.0     What-If Tool TensorBoard plugin.
terminaltables         3.1.0     Generate simple tables in terminals from a nested list of strings.
tifffile               2021.1.8  Read and write TIFF(r) files
torch                  1.7.1     Tensors and Dynamic neural networks in Python with strong GPU acceleration
torchvision            0.8.2     image and video datasets and models for torch deep learning
tqdm                   4.55.1    Fast, Extensible Progress Meter
typing-extensions      3.7.4.3   Backported and Experimental Type Hints for Python 3.5+
urllib3                1.22      HTTP library with thread-safe connection pooling, file post, and more.
werkzeug               1.0.1     The comprehensive WSGI web application library.
```

We will add poetry in the future to keep further track of all dependency versions.

**Comment by Flova** [comment]
This list has some development deps btw.

**Comment by Mffff666** [comment]
> This list has some development deps btw.

I think my problem has been solved !
Thanks.

**Comment by iamstupidd** [comment]
hey bro, i wonder know how do you deal with it,thanks

**Comment by Mffff666** [comment]
I just update the version of pytorch and it works.



---Original---
