### ISSUE TITLE
在执行train文件中出现了如下错误

### ISSUE THREAD

**Issue by Zzheng-6** [eriklindernoren/PyTorch-YOLOv3#625]
能否帮忙解答一下如下错误！Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\PyCharm Community Edition 2020.3.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm Community Edition 2020.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Administrator/Desktop/PyTorch-YOLOv3-master/train.py", line 105, in <module>
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")):
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1166, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\Administrator\Desktop\PyTorch-YOLOv3-master\utils1\datasets.py", line 130, in collate_fn
    paths, imgs, bb_targets = list(zip(*batch))
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by Flova** [comment]
Seems like your dataset is empty. Are you using something like coco or a custom dataset?

**Comment by Zzheng-6** [comment]
Yes,I use coco,it's not empty,when I run train.py,I falied.It always shows this error message.

**Comment by Flova** [comment]
Is this issue still occurring?

**Comment by Zzheng-6** [comment]
This mistake is gone, but a new one has appeared






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] 在执行train文件中出现了如下错误 (#625)





 
Is this issue still occurring?

**Comment by Flova** [comment]
Ok I would close this issue for now and we discuss the other issue in another one okay?

**Comment by Zzheng-6** [comment]
ok,thank you------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月17日(星期三) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] 在执行train文件中出现了如下错误 (#625)

**Comment by yuanqiyin** [comment]
你好，麻烦问下您问题是怎么解决的么，我是用了自己的数据集，也出现了这样的错误，谢谢您
