### ISSUE TITLE
When I run train.py with my own data set, I failed

### ISSUE THREAD

**Issue by Zzheng-6** [eriklindernoren/PyTorch-YOLOv3#633]
The error is as follows:
Training Epoch 0:   0%|          | 0/4 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "E:/PyTorch-YOLOv3-master/train.py", line 111, in <module>
    loss, outputs = model(imgs, targets)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    self.forward(*input, **kwargs)
  File "E:\PyTorch-YOLOv3-master\models.py", line 251, in forward
    x = module(x)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 749, in _call_impl
    return result
UnboundLocalError: local variable 'result' referenced before assignment

Process finished with exit code 1

**Comment by Flova** [comment]
Whats your PyTorch Version?

**Comment by Flova** [comment]
Did you change the Model layout?

**Comment by Zzheng-6** [comment]
I just changed classes to 3,The version of pytorch I use is 1.7.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月19日(星期五) 晚上10:38
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] When I run train.py with my own data set, I failed (#633)





 
Did you change the Model layout?

**Comment by Flova** [comment]
Did you also touch the filters before the yolo layer when changing the classes?

**Comment by Flova** [comment]
I use the same torch version

**Comment by xgyyao** [comment]
@Zzheng-6 filters and classes should be both changed

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
