### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Jingzhuo-Liang** [eriklindernoren/PyTorch-YOLOv3#635]
When I run the command ` python train.py --data_config config/coco.data  --pretrained_weights weights/darknet53.conv.74
`,  an error occured.
The error is as follows:
`Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/coco.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, logdir='logs', model_def='config/yolov3.cfg', multiscale_training=True, n_cpu=8, pretrained_weights='weights/darknet53.conv.74', verbose=False)
2021-02-27 17:14:10.435773: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Training Epoch 0:   0%|          | 0/14658 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 105, in <module>
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")):
  File "D:\anaconda\lib\site-packages\tqdm\_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\anaconda\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
`

Is there an easy way to get rid of this issue?
thanks

**Comment by Flova** [comment]
This seems to be an common issue with PyTorch on Windows.
See this issue: https://github.com/pytorch/pytorch/issues/2341

I primarily maintain this Repo on Linux which makes it hard to reproduce for me. Maybe try setting `--n_cpu` to `0`. This should disable multiprocessing but it comes with an performance penalty.
