### ISSUE TITLE
RuntimeError: DataLoader worker (pid 15713) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by L-QF** [eriklindernoren/PyTorch-YOLOv3#638]
Nvidia Xavier NX
ubuntu 18.04
python 3.6.12

When I use train.py ,I get 
**RuntimeError: DataLoader worker (pid 15713) is killed by signal: Killed**
however I use Example or my trained data

question:it seemly use cpu and cpu may few ,burt  I want to use gpu.
because I have never used Jestson NX

Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, logdir='logs', model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None, verbose=False)
Training Epoch 0:   0%|                                   | 0/5 [01:25<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 111, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/PyTorch-YOLOv3/models.py", line 251, in forward
    x = module(x)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/home/nvidia/miniforge-pypy3/envs/yolov3-PyTorch/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()

**Comment by Flova** [comment]
Your training only uses CPU if I understand you right?
It uses both GPU and CPU in a normal scenario. Data augmentation and data loading are done on the CPU while the Network itself runs on the GPU. To support the GPU you need CUDA. Check `nvidia-smi` to see your GPU and CUDA status.
