### ISSUE TITLE
RuntimeError: DataLoader worker is killed by signal

### ISSUE THREAD

**Issue by mimslim** [eriklindernoren/PyTorch-YOLOv3#650]
My most recent training has died twice at about the same place (epoch 14).
Any ideas as to what might be the cause?
-------------------------------------------------------------------------------------
Training Epoch 13: 100% 101/101 [01:54<00:00,  1.14s/it]

---- Evaluating Model ----
Detecting objects: 100% 13/13 [00:04<00:00,  2.66it/s]
Computing AP: 100% 1/1 [00:00<00:00, 1576.81it/s]
+-------+------------+---------+
| Index | Class name | AP      |
+-------+------------+---------+
| 0     | Box        | 0.92352 |
+-------+------------+---------+
---- mAP 0.9235236715367303
Training Epoch 14:   0% 0/101 [00:00<?, ?it/s]src/tcmalloc.cc:283] Attempt to free invalid pointer 0x1 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2256) is killed by signal: Aborted. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 105, in <module>
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 2256) exited unexpectedly
Training Epoch 14:   0% 0/101 [00:00<?, ?it/s]

**Comment by Flova** [comment]
Maybe try to set`n_cpu=0` or `n_cpu=1`. This should produce a more useful error message.

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by mimslim** [comment]
Sorry, I had a disk crash.   Won’t be able to retest this for another week.

-steve

**Comment by Flova** [comment]
Oh I am sorry. Good luck with your recovery. Don't hurry.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
