### ISSUE TITLE
Bug ：valueerror

### ISSUE THREAD

**Issue by yuanqiyin** [eriklindernoren/PyTorch-YOLOv3#712]
File "E:/PersonalFile/Code/PyTorch-YOLOv3-master/pytorchyolo/train.py", line 262, in <module>
    run()
  File "E:/PersonalFile/Code/PyTorch-YOLOv3-master/pytorchyolo/train.py", line 160, in run
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")):
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\PesonalSoftWare\Anoconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "E:\PersonalFile\Code\PyTorch-YOLOv3-master\pytorchyolo\utils\datasets.py", line 127, in collate_fn
    paths, imgs, bb_targets = list(zip(*batch))
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by yuanqiyin** [comment]
@Flova @Zzheng-6 Can you help me ? Thanks.

**Comment by Flova** [comment]
Please provide the information requested in the template. It is otherwise very hard to identify the cause of this issue. The provided traceback shows that you loaded an empty batch, meaning it does not contain any images. This is most likely the case because something is wrong with your dataset, which results in no loaded images. If you provided further information this would be visible in the logs, because there is a printout for every failed image. So check if your dataset is structured as described in the readme.

**Comment by yuanqiyin** [comment]
Thank you for your reply!


 I have solved this bug now. 

One is the model does not match, and the corresponding classes and filters need to be modified.
 The other is the absolute path and relative path of the generated file.
 Just modify the relative path to the absolute path.
Thanks again.

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 晚上8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] Bug ：valueerror (#712)





 
Please provide the information requested in the template. It is otherwise very hard to identify the cause of this issue. The provided traceback shows that you loaded an empty batch, meaning it does not contain any images. This is most likely the case because something is wrong with your dataset, which results in no loaded images. If you provided further information this would be visible in the logs, because there is a printout for every failed image. So check if your dataset is structured as described in the readme.
