### ISSUE TITLE
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by pengyongrong** [eriklindernoren/PyTorch-YOLOv3#79]
hello author,i have meet some error in using your code,how can i solve it?
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    loss = model(imgs, targets)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/PyTorch-YOLOv3/models.py", line 259, in forward
    x, *losses = module[0](x, targets)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/PyTorch-YOLOv3/models.py", line 202, in forward
    loss_cls = (1 / nB) * self.ce_loss(pred_cls[mask], torch.argmax(tcls[mask], 1))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/functional.py", line 374, in argmax
    return torch._argmax(input, dim, keepdim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by ShiinaMitsuki** [comment]
same error here

**Comment by DreamitDoItFrom0** [comment]
> @pengyongrong @Muthu2093
> I figure it out.
> just place your dataset files and labels as follow:
> 
> ```
> .
> ├── images
> │   ├── annotations
> │   ├── train2014
> │   └── val2014
> └── labels
>     ├── train2014
>     └── val2014
> ```
> it's caused by the failure of loading label file.

I use cocodataset but it doesn't work, the way you said is useful on coco?
